### ISSUE TITLE
kill_workspace()/killWorkspace() returns too quickly

### ISSUE THREAD

**Issue by danielcotton** [quaquel/pyNetLogo#10]
The killWorkspace() Java method seems to interrupt the NetLogo thread, but doesn't seem to wait for the thread to respond to the interruption signal. This results in the kill_workspace() function potentially returning before NetLogo has closed.

This seems to cause some odd crashes, especially when running consecutive simulations.

**Comment by quaquel** [comment]
I am using the kill workspace java code that is also used in the R and Mathematica netlogo links. As noted in the java code comment: 

```java
	/**
	*  it is not possible to close NetLogo by its own closing method, 
	*  because it is based on System.exit(0) which will result in a 
	*  termination of the JVM, jpype and finally python. Therefore, we 
	*  only dispose the thread, we can find. This is the identical to
	*  how it is done in RNetLogo.
	*/
```

note that killing the workspace shuts down netlogo. In general if you want to run many simulations, this is a very bad idea. Restarting Netlogo after each simulation is a waste of compute time.
