### ISSUE TITLE
Netlogo Extension not found

### ISSUE THREAD

**Issue by mkjoy** [quaquel/pyNetLogo#11]
Hello,
I want to use pynetlogo on a netlogo file that includes a netlogo extension. I use the extension nw for network applications, which is properly installed and when opening netlogo without python, it works just fine. However, using pynetlogo gives me an error, stating that the extension cannot be found.

**Comment by tfrench** [comment]
It works if you put the NetLogo extensions folder in the same directory as the python code. 

More info here: https://github.com/NetLogo/NetLogo/wiki/Controlling-API#current-working-directory

**Comment by mkjoy** [comment]
Thank you, problem solved.
