### ISSUE TITLE
ipyparallel with pynetlogo Example 2 not working

### ISSUE THREAD

**Issue by mkjoy** [quaquel/pyNetLogo#12]
I found an Example to parallelize simulations for pynetlogo using ipyparallel documented [here](https://pynetlogo.readthedocs.io/en/latest/example2.html): 
Example 2: Sensitivity analysis for a NetLogo model with SALib and ipyparallel

Following this guide, I cannot perform the simulations due to an error given when using the `map_sync` method. I have tested if netlogo loads properly, which is does. The code I use and the resulting error are given in the following. I sticked simply to the original code provided in the link above with some minor adaptions of `netlogo_home, netlogo_version, cwd, n` and ticks.

```
#Ensuring compliance of code with both python2 and python3

from __future__ import division, print_function
try:
    from itertools import izip as zip
except ImportError: # will be 3.x series
    pass
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('white')
sns.set_context('talk')


import pyNetLogo

#Import the sampling and analysis modules for a Sobol variance-based
#sensitivity analysis
from SALib.sample import saltelli
from SALib.analyze import sobol

problem = {
  'num_vars': 6,
  'names': ['random-seed',
            'grass-regrowth-time',
            'sheep-gain-from-food',
            'wolf-gain-from-food',
            'sheep-reproduce',
            'wolf-reproduce'],
  'bounds': [[1, 100000],
             [20., 40.],
             [2., 8.],
             [16., 32.],
             [2., 8.],
             [2., 8.]]
}

n = 1 #test value
param_values = saltelli.sample(problem, n, calc_second_order=True)

#param_values.shape


import ipyparallel

client = ipyparallel.Client()
#client.ids

direct_view = client[:]

import os

#Push the current working directory to a "cwd" variable on the engines that can be accessed later
direct_view.push(dict(cwd=os.getcwd()))
cwd=os.getcwd()

#Push the "problem" variable from the notebook to a corresponding variable on the engines
direct_view.push(dict(problem=problem))

##%%px

import os
os.chdir(cwd)

import pyNetLogo
import pandas as pd

netlogo = pyNetLogo.NetLogoLink(gui=False, \
                                netlogo_version = "6", \
                                netlogo_home = "D:\\Programme\\Netlogo" \
                                )
netlogo.load_model(r'Wolf Sheep Predation_v6.nlogo')


def simulation(experiment):

    #Set the input parameters
    for i, name in enumerate(problem['names']):
        if name == 'random-seed':
            #The NetLogo random seed requires a different syntax
            netlogo.command('random-seed {}'.format(experiment[i]))
        else:
            #Otherwise, assume the input parameters are global variables
            netlogo.command('set {0} {1}'.format(name, experiment[i]))

    netlogo.command('setup')
    #Run for 100 ticks and return the number of sheep and wolf agents at each time step
    counts = netlogo.repeat_report(['count sheep','count wolves'], 1)

    results = pd.Series([counts['count sheep'].values.mean(),
                         counts['count wolves'].values.mean()],
                         index=['Avg. sheep', 'Avg. wolves'])

    return results

lview = client.load_balanced_view()

results = pd.DataFrame(lview.map_sync(simulation, param_values))

results.to_csv('Sobol_parallel.csv')

results.head(5)
```

Resulting in multiple Error messages:

```
[0:apply]: 
---------------------------------------------------------------------------NameError                                 Traceback (most recent call last)<string> in <module>()
d:\programme\anaconda\lib\site-packages\ipyparallel\client\remotefunction.py in <lambda>(f, *sequences)
    141 
    142 if sys.version_info[0] >= 3:
--> 143     _map = lambda f, *sequences: list(map(f, *sequences))
    144 else:
    145     _map = map
C:/Users/..../myfile.py in simulation(experiment)
     88         if name == 'random-seed':
     89             #The NetLogo random seed requires a different syntax
---> 90             netlogo.command('random-seed {}'.format(experiment[i]))
     91         else:
     92             #Otherwise, assume the input parameters are global variables
NameError: name 'netlogo' is not defined

10 more exceptions ...
```

**Comment by quaquel** [comment]
do you run this using a jupyter notebook, for that is the intended use case of ipyparallel

**Comment by mkjoy** [comment]
No, I use spyder. Is this not an option when leaving out `%%px` ?

**Comment by quaquel** [comment]
%%px is a jupyter magic for executing the code in that cell on all engines. I am not certain how to translate this to the equivalent for spyder. Possibly by having %px in front of all the code between %%px and lview

However, if you want to run within a normal python file, I would use multiprocessing instead of ipyparallel.

**Comment by quaquel** [comment]
I have added a multiprocessing example to the documentation

**Comment by NaibafR** [comment]
I am running several NetLogo simulations simultaneously by using multiprocessing. However, sometime the job exits with the following error (this is just an example):

FileNotFoundError: [Errno 2] No such file or directory: '/cluster/home/fabiarot/-9223369057811614078_real-month.txt'

Could it be that the temporary created text files by the command `repeat_report`  have the same file name across several simultaneous simulations / processes and as a consequence get overwritten or already deleted by another simulation / process which leaves the second process looking for its file which is not there anymore?

I have had this error a few times and now tried to individualize the file names by just adding a random integer to it as follows:

```
        fn = r'{0}{1}{2}_{3}_{4}{5}'.format(os.getcwd(),
                                        os.sep,
                                        hash(self),
                                        variable,
                                        random.randint(0, 999999999999),
                                        '.txt')
```

It seems to work but I do not have long term experience with it.

If you think my guess could be true maybe you want to fix it in the package.

Thank you and best,

Fabian

**Comment by quaquel** [comment]
Others were having a similar problem. There is a fix on master, I hope to make a new version available on pip before christmas with this and a few other fixes.

**Comment by quaquel** [comment]
I have pushed version 0.3 to pip, so you could simply update now.
