### ISSUE TITLE
Parameter optimization using "ipyparallel"

### ISSUE THREAD

**Issue by NaibafR** [quaquel/pyNetLogo#14]
Hi, I would like to determine the value of a certain input variable of my NetLogo file in order to get an output result that matches a predefined value best (Optimisation of input value).
Therefore I would like to...
(1.1) ... set a particular value for my input variable and run the program 100 times for this input value,
(2.1) ... take the median of the results of all 100 runs and compare this median to my intended output value,
(1.2) ... adjust the value for my input variable and run the program again 100 times for the new input value,
(2.2.) ... and so on.

While just using one core of my cpu it works fine. Now, in order to speed the process up I would like to parallelize the simulations. This means, I would like to distribute the 100 runs to all my cpu cores, then analyse the median result, set a new input value and again distribute the next 100 runs across the cores.

Optimally I would like to only define the particular input value for which the program needs to be executed 100 times while the distribution of the runs across the cores is managed automatically.

Every of the 100 runs starts with a new complete setup of the program and undergoes the go-procedure a predetermined amount of times.

Does anyone have an idea how to implement this best? :)
Thank you!

**Comment by quaquel** [comment]
Are you running on a single machine, or on a cluster? 

Have a look at the ipyparallel example that comes with the code and is discussed in the associated JASSS journal paper (http://jasss.soc.surrey.ac.uk/21/2/4.html) An approach like this should be quite easy to adapt to an optimisation context. Have a main process that runs the optimiser and generates the tasks. Farm out the tasks to a pool (multiprocessing pool, ipyparralel pool)

**Comment by NaibafR** [comment]
I am running the program on a single machine.

I had a look at the example but did not really understand what was happening there to be honest given that I am new to python and not too familiar with all the packeges included. In addition I do not really want to perform a sensitivity analysis. I think my intention should even be easier.

```
import ipyparallel

client = ipyparallel.Client()
client.ids

%%px 

import os
os.chdir(cwd)

import pyNetLogo
import pandas as pd

netlogo = pyNetLogo.NetLogoLink(gui=False)
netlogo.load_model(r'00_Model_ES_PV_Policy/PV_Policy_Spain.nlogo')

def run_simulation(input_value):
    netlogo.command('setup')
    netlogo.command('set fixed-degression-rate %s' % (input_value))
    # Execute the go-procedure of netlogo 253 times and write the following values for each month into a Panda DataFrame called "results"
    results = netlogo.repeat_report(['real-month','year','calendar-month','monthly-installed-capacity','monthly-policy-goal','policy-cost-month'], 253, go='go')
    # Calculate the absoulte monthly policy goal deviations and write them into a new DataFrame called "monthlydeviations"
    monthlydeviations = abs(results.loc[:,'monthly-installed-capacity'] - results.loc[:,'monthly-policy-goal'])
    # Calculate the sum of the absolute deviations and write it into a new DataFrame calles "sumofmonthlydeviations"
    sumofmonthlydeviations = sum(monthlydeviations)
    # Return the final result called "sumofmonthlydeviations"
    return sumofmonthlydeviations
...

```

This is where I am at the moment. Now I would like to run the function `run_simulation` 100 times, distributed across different cpu cores and get back a data frame that contains all 100 `sumofmonthlydeviations`, analyse the result and call the function `run_simulation` again 100 times but now with a different `input_value`.

**Comment by quaquel** [comment]
Have a look at the concurrent.futures package and specifically the ProcessPoolExecutor: https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor

It should be quite straightforward to adapt their primes example to an optimisation use case. However, do pass an initializer function as a keyword argument. This function will be called by each process after it has been started. You can load the netlogo model within this initializer function.

so:

```python

def initialiser():
    netlogo = pyNetLogo.NetLogoLink(gui=False)
    netlogo.load_model(r'00_Model_ES_PV_Policy/PV_Policy_Spain.nlogo')

def run_simulation(input_value):
    netlogo.command('setup')
    netlogo.command('set fixed-degression-rate %s' % (input_value))
    # Execute the go-procedure of netlogo 253 times and write the 
    # following values for each month into a Panda DataFrame called "results"
    results = netlogo.repeat_report(['real-month', 'year',
                                     'calendar-month',
                                     'monthly-installed-capacity',
                                     'monthly-policy-goal',
                                     'policy-cost-month'],
                                     253, go='go')
    # Calculate the absoulte monthly policy goal deviations and write 
    # them into a new DataFrame called "monthlydeviations"
    monthlydeviations = abs(results.loc[:,'monthly-installed-capacity'] - results.loc[:,'monthly-policy-goal'])
    # Calculate the sum of the absolute deviations and write it into a new DataFrame 
    # called "sumofmonthlydeviations"
    sumofmonthlydeviations = sum(monthlydeviations)
    # Return the final result called "sumofmonthlydeviations"
    return sumofmonthlydeviations


with concurrent.futures.ProcessPoolExecutor(initializer= initialiser) as executor:
    # optimisation code goes here

```

Are you on a windows machine or something else? This has implication for how to develop the code further. 

If you have any further questions, don't hesitate to ask.

**Comment by NaibafR** [comment]
I am on a windows machine using jupyter.

I already tried multiprocessing in general which unfortunately did not work. I don't know if this is a necessary basis to make the "concurrent.futures" package to work.

If I try multithreading, the following code runs fine:

```
from threading import Thread
import time

def f(i):
    for n in i:
        time.sleep(0.5)
        print(n)

if __name__ == '__main__':
    start_time = time.time()
    arr1 = [1,2,3,4,5]

    p1 = Thread(target=f, args=(arr1,))
    p1.start()
    p1.join()

    print("--- %s seconds ---" % (time.time() - start_time))
```

However, if I try the same example just with multiprocessing, nothing happens, meaning there is no error arising and it just prints out the total run time which is far below 1 second, meaning that it has not gone through the `time.sleep(0.5)` at all.

```
from multiprocessing import Process
import time

def f(i):
    for n in i:
        time.sleep(0.5)
        print(n)

if __name__ == '__main__':
    start_time = time.time()
    arr1 = [1,2,3,4,5]

    p1 = Process(target=f, args=(arr1,))
    p1.start()
    p1.join()

    print("--- %s seconds ---" % (time.time() - start_time))
```

If I follow your suggestion I do not get a speed increase so far. At least to me it does not seem as if there were multiple processes started at the same time on multiple cpu cores. If I execute the following code, there is no difference in the run time between `max_workers=1` and `max_workers=2`.

```
import concurrent.futures
import time

def test():
    time.sleep(1)
    print('1')

def main():
    #with concurrent.futures.ProcessPoolExecutor() as executor:
    with concurrent.futures.ProcessPoolExecutor(max_workers=2) as executor:
        for i in range(5):
            test()

if __name__ == '__main__':
    start_time = time.time()
    main()
    print("--- %s seconds ---" % (time.time() - start_time))
```

**Comment by quaquel** [comment]
Multiprocessing is a rather complicated topic on a windows machine. Moreover, you have to account for the fact that starting processes takes time. You only start to see performance differences if the time for the tasks is larger than the time required for starting the processes. So if you make your sleep longer, and you increase range to say 100, you should start to see a difference.

Better yet, look at e.g. https://docs.python.org/2/library/multiprocessing.html#using-a-pool-of-workers for some more examples and discussion. The concurrent.futures is a wrapper around the pool of multiprocessing. In general, it is recommended to use the concurrent.futures executor.

**Comment by quaquel** [comment]
I have added a multiprocessing example to the documentation.

**Comment by NaibafR** [comment]
> 
> 
> Multiprocessing is a rather complicated topic on a windows machine. Moreover, you have to account for the fact that starting processes takes time. You only start to see performance differences if the time for the tasks is larger than the time required for starting the processes. So if you make your sleep longer, and you increase range to say 100, you should start to see a difference.

Unfortunately, even if I make my sleep longer and if I increase the range I do not see a difference. The `print('1')` is always executed perfectly with an interval matching the defined `time.sleep(5)` seconds even for multiple workers such as `(max_workers=2)`.

PS: I know, that this is not a problem that belongs into the pyNetLogo section anymore as by now I am discussing a general multiprocessing problem here.

**Comment by quaquel** [comment]
the problem is that your code is not correct. 

You do

```python
        for i in range(5):
            test()
```

but then you just call test directly, rather than calling test through the executor.

```python
    executor.map(sleep, [_ for _ in range(5)]
```

so, call the function through the executor.
