### ISSUE TITLE
fixing problems with JPype1

### ISSUE THREAD

**Issue by terna** [quaquel/pyNetLogo#16]
Just an info.

I use Python 3. It was impossible to link java components until I moved to the JPype1 version that you can find at https://pypi.org/project/JPype1-py3/

Install with 
pip install JPype1-py3

Best, Pietro

**Comment by quaquel** [comment]
Thank you, it useful to know that a pip version is available. In general, I recommend using conda for jpype, rather than pip. See also: https://jpype.readthedocs.io/en/latest/install.html

**Comment by Westlife1002** [comment]
I cannot install with "pip install JPype1-py3".  the error message says "error: Microsoft Visual C++ 14.0 is required."
what is the fix for this issue?

**Comment by quaquel** [comment]
you really need to provide more context. I have no idea what kind of system you are working on, which python version you are using, which distribution, etc. My general advise is to use conda rather than pip for jpype. Other jpype questions should go to jpype and don't belong here.
