### ISSUE TITLE
[Question] Referencing this repository

### ISSUE THREAD

**Issue by brendenpetersen** [quaquel/pyNetLogo#18]
How should this repository be cited if used for a scientific publication? Perhaps the reference info could be added to the README?

EDIT: I just noticed the following publication: https://pure.tudelft.nl/portal/files/44031616/4.pdf. Should I just reference this?

**Comment by quaquel** [comment]
please cite the paper in JASSS: http://jasss.soc.surrey.ac.uk/21/2/4.html 

I will update the README

**Comment by brendenpetersen** [comment]
Thanks so much!
