### ISSUE TITLE
Flexibly change the variable value

### ISSUE THREAD

**Issue by Westlife1002** [quaquel/pyNetLogo#19]
Is there a way to systematically change the variable value (e.g. sheep/wolf qty) in the netlogo.command() where the variable is surrounded by the quotes...

![5](https://user-images.githubusercontent.com/34776946/51125786-5eea9300-185c-11e9-89ae-26ce73bbefa2.png)

**Comment by quaquel** [comment]
I am not sure what you are asking. Are you asking how to handle variables where the netlogo name contains quotes?

**Comment by Westlife1002** [comment]
Yes, how do I dynamically modify the Netlogo variable values in Python if there are quotes around "set xx yy" in netlogo.command()

**Comment by Westlife1002** [comment]
But this won't work:
netlogo.command('ask sorters with [who < 8] [set capacity_hr ' + str(Get_value(1)) + ']')

"raise NetLogoException(ex.message())
pyNetLogo.core.NetLogoException: Expected closing bracket."

**Comment by quaquel** [comment]
probably the solution is to use double quoted strings with an escape character before the single quote symbol:

```python

some_string= "a string with \'some other embedded\' string"

```
