### ISSUE TITLE
while loop

### ISSUE THREAD

**Issue by dfolch** [quaquel/pyNetLogo#2]
I'm really liking the package. Wondering if pyNetLogo has a direct way of doing a while loop, similar to [NLDoReportWhile](https://www.rdocumentation.org/packages/RNetLogo/versions/1.0-4/topics/NLDoReportWhile) in RNetLogo. Below is my home-brew solution using the built-in segregation model to collect some output and keep running the model until a condition is met. Is there another approach?

```python
import pyNetLogo
import pandas as pd

netlogo = pyNetLogo.NetLogoLink(gui=True)
netlogo.load_model("Segregation.nlogo")
netlogo.command("set density 70")
netlogo.command("set %-similar-wanted 70")
netlogo.command("setup")

unhappy_df_70 = pd.DataFrame()
while True:
    temp = netlogo.repeat_report(["count turtles with [ not happy? ]",  "count turtles"], 1)
    unhappy_df_70 = pd.concat([unhappy_df_70,temp])
    if temp["count turtles with [ not happy? ]"].values == 0:
        break
```

**Comment by quaquel** [comment]
At the moment this function does not exist. Feel free to make a pull request and I will add it in. Otherwise, I hope to get to it somewhere in the near future.
