### ISSUE TITLE
Unable to load NetLogo version 5

### ISSUE THREAD

**Issue by mrn-aglic** [quaquel/pyNetLogo#20]
I am unable to load NetLogo version 5. I keep getting the error java.lang.RuntimeException: Class NetLogoLinkV5.NetLogoLink not found:

```
>>> netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_version='5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyNetLogo/core.py", line 255, in __init__
    link = jpype.JClass(module_name[self.netlogo_version])
  File "/usr/local/lib/python3.7/site-packages/jpype/_jclass.py", line 73, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class NetLogoLinkV5.NetLogoLink not found
```

I'm using macOS Mojave. 
Python version is: Python 3.7.2 installed via Homebrew
Install location for Python: /usr/local/bin/python3
The default java jvm is: 
```
>>> jpype.getDefaultJVMPath()
'/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/lib/jli/libjli.dylib'
```

Version 6 loads normally. However, I do need version 5.

**Comment by quaquel** [comment]
Please provide me with sufficient information to understand the problem. E.g., what OS are you using? which Java version do you have? What version of Python are you using? Do you have short example piece of code I can look at? etc.

Just stating something does not work is not particularly clear nor will it allow me to help you.

**Comment by mrn-aglic** [comment]
> Please provide me with sufficient information to understand the problem. E.g., what OS are you using? which Java version do you have? What version of Python are you using? Do you have short example piece of code I can look at? etc.
> 
> Just stating something does not work is not particularly clear nor will it allow me to help you.

Sorry, I edited my question to include the requested details

**Comment by quaquel** [comment]
ok, I have access to a Mac with Mojave. I will look into this as soon as possible

**Comment by quaquel** [comment]
I tried to replicate your problem and failed to do so when using JupyterLab or Eclipse with pydev. In what environment are you working? I am using the anaconda distribution, rather than homebrew.

To be clear, the code below works fine on my Mac with Mojave. Changing to the latest open jdk also works fine. 

```python
netlogo_home = '/Applications/NetLogo 5.3.1'
netlogo_version = '5'
jvm_home = '/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/MacOS/libjli.dylib'

link = pyNetLogo.NetLogoLink(netlogo_home=netlogo_home, 
                             netlogo_version=netlogo_version,
                             jvm_home=jvm_home)

print(link)

```

**Comment by mrn-aglic** [comment]
I don't get it... it works for me too when I open new notebook, but still doesn't work on old one...

<img width="1552" alt="Screenshot 2019-03-24 at 20 37 24" src="https://user-images.githubusercontent.com/2858231/54884742-c9c7d400-4e74-11e9-840e-8a7d167e975c.png">
<img width="1552" alt="Screenshot 2019-03-24 at 20 37 30" src="https://user-images.githubusercontent.com/2858231/54884743-c9c7d400-4e74-11e9-9018-2efb21445b38.png">

I've tried restarting the kernel on the old notebook... well, I guess that it isn't the issue with pyNetLogo then....
thanks for your time!

**Comment by quaquel** [comment]
Very strange, but similar to something I had. I quickly tested it on Friday using Ipython and replicated your error. Today, I finally had more time to look at it, and failed to replicate the problem. In the meantime, I have restarted my machine a few times (brand new, still installing stuff). Anyway, glad the problem seems gone. 

Note that you should pass netlogo_home as well, not just '5'. I load all the jars from netlogo_home, so if home points to 6, while you use the link for 5 weird stuff will happen.

**Comment by mrn-aglic** [comment]
The problem disappeared after I restarted jupyter notebook. When the problem first appeared, the first thing I did was reinstall anaconda... Must have been something wrong with the first install (the most obvious conclusion). 

It also works with brew python3 when both netlogo_version and netlogo_home are passed as parameters... It doesn't work when only the version is set for NetLogo 5, but still works for NetLogo 6.

Anyway thanks for all of your help. I guess I just need to set netlogo_home and netlogo_version

**Comment by quaquel** [comment]
this has to do with the automatic identification of netlogo_home which defaults to the most recent version. I can probably modify this a bit making it no longer necessary to supply both netlogo_home and netlogo_version. I will keep this issue open for now.
