### ISSUE TITLE
"Duplicate Keys not allowed" error for repeated execution

### ISSUE THREAD

**Issue by steipatr** [quaquel/pyNetLogo#22]
I wrote a Python function to extract views/snapshots from NetLogo runs. Eventually I want to generate GIFs, MP4s etc. of the runs. The function imports pyNetLogo, loads a specified model, runs it until the desired tick, saves the world view of the tick, and kills NetLogo. This works fine when executed once, but the second execution (e.g. for a different model file) hangs or returns an error (see attached). Restarting the Python kernel resets the issue, but I am hoping there is a smoother option, or I am missing something?

Possibly related to https://github.com/quaquel/pyNetLogo/issues/10 ?

Versions:
- Windows: 7 Enterprise, SP1
- Python: 3.6
- Jupyter Notebook: 5.0
- pyNetLogo: 0.3
- Java: 8 Update 201 (build 1.8.0_201-b09)
- NetLogo: 6.0.2

Attached in ZIP:
- minimal working example Jupyter notebook
- two NetLogo model files to go with the notebook
- screenshot of the error message which sometimes appears

[pyNetLogo Duplicate Keys Error.zip](https://github.com/quaquel/pyNetLogo/files/3116007/pyNetLogo.Duplicate.Keys.Error.zip)

**Comment by quaquel** [comment]
try:

```Python

import pyNetLogo
netlogo = pyNetLogo.NetLogoLink(gui=True)
netlogo.load_model(str(model))

def export_frame(model,frame,setup='Setup',go='[go]'):
    # setup should clear all globals etc. So have a 
    # clean sheet for running the model
    netlogo.command(setup)
    print("5")
    
    netlogo.command('repeat ' + str(frame) +  go)
    print("6")
    
    netlogo.command('export-view \"' + str(frame) + '.png\" ')
    print("7")
    
    
    return

```

**Comment by steipatr** [comment]
With `model = "Ticker.nlogo"` as the first line to preempt `NameError: name 'model' is not defined` being thrown by `netlogo.load_model`, moving the import and loading outside works. But it also defeats my intended purpose of the self-contained function, since I can no longer pass the model file as an argument.

I believe the issue generalizes to pyNetLogo not being able to connect to multiple models at once?

```
import pyNetLogo
netlogo1 = pyNetLogo.NetLogoLink(gui=True)
netlogo2 = pyNetLogo.NetLogoLink(gui=True)
netlogo1.load_model(str('Ticker.nlogo'))
netlogo2.load_model(str('Wolf Sheep Gore.nlogo'))
```

... gives the same error message, the models being loaded sequentially in the same NetLogo window.

**Comment by quaquel** [comment]
```python

import pyNetLogo
netlogo = pyNetLogo.NetLogoLink(gui=True)


def export_frame(model,frame,setup='Setup',go='[go]'):
    netlogo.load_model(str(model))
    # setup should clear all globals etc. So have a 
    # clean sheet for running the model
    netlogo.command(setup)
    print("5")
    
    netlogo.command('repeat ' + str(frame) +  go)
    print("6")
    
    netlogo.command('export-view \"' + str(frame) + '.png\" ')
    print("7")
    
    
    return

```

does this work?

**Comment by steipatr** [comment]
Oh, duh. Yes that's perfectly fine.

I want to eventually/maybe turn this into a distributable Python package for exporting animations from Netlogo, so the reason why I wanted to keep everything inside a single function was to facilitate that down the line. But apparently Python actually executes packages on import, so would it be appropriate to have 

```python
import pyNetLogo
netlogo = pyNetLogo.NetLogoLink(gui=True)
```

at the beginning of the package to instantly create the NetLogo link? and then have `export_frame` etc. as actual functions to be called as needed?

**Comment by quaquel** [comment]
exactly, instantiating the netlogo link is like opening NetLogo. Why would you close netlogo if you can just as well simply open another model?
