### ISSUE TITLE
InvocationTargetException when opening model Linux

### ISSUE THREAD

**Issue by hull-colasanti** [quaquel/pyNetLogo#23]
I am running Ubuntu 18.10
Python 3.6.7 in  virtualenv
Jupyter notebook
Oracle Java 11
NetLogo 6.1.0

import pyNetLogo
netlogo = pyNetLogo.NetLogoLink(gui=True,netlogo_home='/home/ric/Software/NetLogo/', netlogo_version='6')
this  does start nlogo
netlogo.load_model('/home/ric/Projects/NetLogo/agent01.nlogo')
this produces a InvocationTargetException form NetLogo
when dismissed produces the following from the python code
java.lang.RuntimeExceptionPyRaisable      Traceback (most recent call last)
~/Projects/Python/env/lib/python3.6/site-packages/pyNetLogo/core.py in load_model(self, path)
    282         try:
--> 283             self.link.loadModel(path)
    284         except jpype.JavaException as ex:

java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException

During handling of the above exception, another exception occurred:

NetLogoException                          Traceback (most recent call last)
<ipython-input-4-4f30048de2c3> in <module>
----> 1 netlogo.load_model('agent01.nlogo')

~/Projects/Python/env/lib/python3.6/site-packages/pyNetLogo/core.py in load_model(self, path)
    283             self.link.loadModel(path)
    284         except jpype.JavaException as ex:
--> 285             raise NetLogoException(ex.message())
    286
    287     def kill_workspace(self):

NetLogoException: None

I have tried placing the netlogo model in the same directory and replacing it with a model from the examples

However
If i run
netlogo = pyNetLogo.NetLogoLink(gui=True,netlogo_home='/home/ric/Software/NetLogo/', netlogo_version='6')

then open the file from within the netlogo running instance ( ie from the menu)
I can call the procedures from with in the jupyter script
ie
netlogo.command('setup')
will work.
So the problem is in loading the model with load_model

I cant see any other attributes that are required for load_model from the documentation.
What am I doing wrong?
Your help would be much appreciated

**Comment by hull-colasanti** [comment]
This appears to be a problem with using NetLogo6.1
With Netlogo 6.0.4
Ubuntu 18.10
Python 3.6.7 in  virtualenv
Jupyter notebook
Oracle Java 11
this works

**Comment by quaquel** [comment]
this is the same issue as #24, which is now fixed in master. Expect a new release this month
