### ISSUE TITLE
jpype.startJVM arguments

### ISSUE THREAD

**Issue by brodderickrodriguez** [quaquel/pyNetLogo#26]
line 245 in core.py causing a TypeError due to argument 'convertStrings':
`TypeError: startJVM() got an unexpected keyword argument 'convertStrings'
`
After removing this argument everything executes as expected. Please update the except case to try to start JVM without this parameter. 

line 245: 
`                jpype.startJVM(jvm_home, convertStrings=False, *jvm_args)`

**Comment by quaquel** [comment]
which version of jpype are you using?

**Comment by NedaMarvasti** [comment]
Hi I have the same problem and Jpype1 version is 0.6.3.

**Comment by quaquel** [comment]
To be clear, pynetlogo 0.4 requires jpype 0.7 or newer.

**Comment by brodderickrodriguez** [comment]
I was using jpype 0.6.3 with pynetlogo 0.4.0. 
After downgrading to pynetlogo 0.3.0 this issue resolved itself.

**Comment by quaquel** [comment]
or upgrading to jpype 0.7.

Pynetlogo 0.4 contains also some bug fixes.

**Comment by brodderickrodriguez** [comment]
Confirmed that that combination works as well.

**Comment by brodderickrodriguez** [comment]
Thank you Jan!
