### ISSUE TITLE
repeat_report doesn't report final tick

### ISSUE THREAD

**Issue by qiemem** [quaquel/pyNetLogo#30]
For instance:
```
> print(netlogo.repeat_report(["ticks"], 1))

     ticks
0.0      0

> print(netlogo.repeat_report(["ticks"], 1))

     ticks
1.0      1

> print(netlogo.repeat_report(["ticks"], 1))

     ticks
2.0      2
```

As can be seen here, `go` is being called once on each call. The output of reporters is being returned from before the call but not after the call. That is, you get the initial state of the model but not the final state of the model.

**Comment by quaquel** [comment]
that clearly is a bug. I had a quick look at the underlying code and this should not be too difficult to fix. Will try fix it before Christmas.

**Comment by quaquel** [comment]
I have been looking at the Mathematica Link for NetLogo. See [here](https://github.com/NetLogo/Mathematica-Link/blob/64bf9e35db7eaf783b7b3d398239ec6c6080f01d/src/main/NLink.java). 

the repeat_report functionality is handled by the doReport method in Lin e 107. Here they first do a command, followed by a reporter call. In this case, you will miss the value at tick 0. 

My approach is a bit different. I push the repeat_report into a long string which is completely executed in NetLogo (Scala). This is from testing with 5.X about 10 times faster than having a loop executing in java. The drawback of my implementation is that it will get the value at the current tick, and next executes a tick. 

Not sure what the preferred solution is.

**Comment by qiemem** [comment]
>  The drawback of my implementation is that it will get the value at the current tick, and next executes a tick.

Looking at the code, I don't think this is inherent drawback of your implementation. If you append another instance of `c_middle` at the end of the concatenation [here](https://github.com/quaquel/pyNetLogo/blob/master/pyNetLogo/core.py#L572), it should record another instance of all the reporters after the last tick. Let me know if you'd like a PR to this effect, or if you prefer to just do it.

> My approach is a bit different. I push the repeat_report into a long string which is completely executed in NetLogo (Scala). This is from testing with 5.X about 10 times faster than having a loop executing in java.

I noticed this! Nice solution and it's impressively fast (especially given that it's going through IO!). It's unfortunate that it's such a pain to intermix commands and reporters from the controlling API.

The main reason it's so slow to keep calling `Workspace.command` from Java (or Python for that matter) is that that keeps compiling the code over and over, and while NetLogo is supposed to be caching compiler results, it's [pretty bad at it](https://github.com/NetLogo/NetLogo/issues/549) (and, to be honest, I can't remember where in the code path the cache gets invoked, so I'm not sure if it's actually hit in `workspace.command`, etc).

However, you can get around this by explicitly compiling the commands with `Workspace.command` and then running with `Workspace.runCompiledCommands` (there are analogous methods for reporters). Here's a comparison of the two methods in Python via jpype (it's the same in Java):

```
%timeit ws.command("ask turtles [ fd 1 ]")

4.06 ms ± 990 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
vs
```
owner = SimpleJobOwner("python", ws.mainRNG(), AgentKindJ.Observer())
cmd = ws.compileCommands("ask turtles [ fd 1 ]")
%timeit ws.runCompiledCommands(owner, cmd)

The slowest run took 4.98 times longer than the fastest. This could mean that an intermediate result is being cached.
32 µs ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

(`ws` is a `Workspace` instance)

That said, implementing `repeat_report` this way still seems to be slower than your implementation. Which makes sense; there's still the overhead here of submitting a bunch of jobs to the NetLogo JobThread and waiting on the result. Like I said, I'm seriously impressed with how fast your implementation is! Still, it's like 10% slower instead of 10x-100x.

It's worth noting that there is another way of getting the results out of NetLogo without going through IO, but it's involves getting into the guts of things. If you're interested, you take code like this (constructed using a similar technique to what you're doing):

```
(run 
  [ collect ->
    (run collect (list (count wolves) (count sheep))
    repeat 1000 [
      go
      (run collect (list (count wolves) (count sheep))
    ]
  ]
  0
)
```
You then take the compiled procedure from this (created as above) and replace the argument (currently `0`) to the outer `run` with a custom implementation of `AnonymousCommand` which collects the results in a data structure that you can read from later. The `AnonymousCommand` implementation is pretty straightforward, but the argument replacement is weird. It looks like this (again, Python code since I've been playing around with, but similar in Java/Scala):

```
collector = CollectorCommand()
runner.code()[0].args[1] = _const(collector)
```

I've been messing around with just doing this in Python (never used JPype before; really fun to play with!) and jpype seems to get in the way a bit here, but LevelSpace does a lot of stuff like this. Anyway, like I said, kind of gross, but it does let you get around the IO if you're interested in that.

**Comment by quaquel** [comment]
the drawback of adding the inner element at the end is that you will always get 1 tick more than the number of ticks you wanted to run. In particular if you use repeat_report several times in a row as in your tick example, you have to be careful with how you concatenate the results. 

How about adding a keyword argument where the user can choose to get the the current value of the report prior to any tick? Basically, move the writing to file after the go, and if some boolean is true, also have one write command before the repeat command. 

Yes this breaks parity with other controlling api's but it is easy to document and an optional argument. 

thanks for the insights into the inner workings of NetLogo. I am not an avid NetLogo user myself, but rather built this library first for a PhD student when I was a postdoc, and later developed it a bit more for one of my own PhD students. Can you point me to any documentation on the compiled command stuff. This is something I would love to try for some large scale computational experimentation with NetLogo models.

**Comment by qiemem** [comment]
> How about adding a keyword argument where the user can choose to get the the current value of the report prior to any tick?

I think that's a great idea.

> Can you point me to any documentation on the compiled command stuff. This is something I would love to try for some large scale computational experimentation with NetLogo models.

Unfortunately, not really. Documentation for the internals of NetLogo is not great. Happy to answer questions though.
