### ISSUE TITLE
Would it be possible to obtain a list of global variables and initial settings when a model is loaded?

### ISSUE THREAD

**Issue by sunil-subbakrishna** [quaquel/pyNetLogo#31]
First of all, thanks for building this package which I am just learning how to use.

Regarding my question, I am envisioning a function called get_globals(), called after the model is loaded. With the wolf and sheep model used to illustrate how pyNetLogo works, a call to get_globals() could return the following dict:

{'grass-regrowth-time': {'minimum': 0, 'increment': 1, 'maximum': 250, 'value': 30}, 
 'sheep-gain-from-food': {as above},
 'wolf-gain-from-food': {as above},
 'sheep-reproduce': {as above},
 'wolf-reproduce': {as above}}

The creation of the dict "problem" could then be partially automated, parameterized, and less dependent on cutting and pasting between the Python script and the NetLogo model. Likewise for the definition of the function run_simulation.

In any case, thanks again for this development. Python and  NetLogo together present some real possibilities for creating very useful ABMs.

**Comment by quaquel** [comment]
what netlogo commands would return the globals?

if you can make an example implementation, I am happy to integrate it into the library.
