### ISSUE TITLE
Netlogo 6.2.0 with pyNetLogo

### ISSUE THREAD

**Issue by KevinLalor** [quaquel/pyNetLogo#38]
Dear Devs,

I'm using Netlogo for my final year project and have ran into issues running the Example1 on your documentation. Below is my code and error.

![image](https://user-images.githubusercontent.com/44394204/106739530-29ff3380-6611-11eb-840c-dba8d297aad2.png)

![image](https://user-images.githubusercontent.com/44394204/106738883-67af8c80-6610-11eb-845e-4f23ad316e56.png)

I'm running windows 10, I have reinstalled netlogo once to see if it was a path issue, It seems to be a version issue and was wondering if pynetlogo works with netlogo 6.2 or should I install an older version.

Java version is:
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Python Version:
Python 3.7.6

Jpype:
![image](https://user-images.githubusercontent.com/44394204/106739420-0936de00-6611-11eb-8e5e-e73b5cfd9a96.png)

**Comment by quaquel** [comment]
at present 6.2 is not yet supported. I have not had a chance to check and see how the java side has been modified.

**Comment by KevinLalor** [comment]
That's no problem, Thank you for the quick reply! What version should I download to be able to use pyNetLogo?

**Comment by quaquel** [comment]
6.1 should work,

but testing with 6.2 should also be quite easy. There are 2 global variables that have netlogo version specific fields. You could add entries here for 6.2 and see if it works.

```python

import pynetlogo

pynetlogo.jar_name['6.2'] = pynetlogo.jar_name['6.1'] 
pynetlogo.class_name['6.2'] = pynetlogo.class_name['6.1']
```

and then do the normal stuff. No idea what will happen, but basically this tells pynetlogo to handle 6.2 in the same way as 6.1

**Comment by KevinLalor** [comment]
okay cool, Ill try that also, Thank you for all the help.

**Comment by KevinLalor** [comment]
Hey, 

I implemented your fix today and got a new error.

TypeError: Class NetLogoLinkV61.NetLogoLink is not found

![image](https://user-images.githubusercontent.com/44394204/106895232-e3303d00-66e7-11eb-9f1c-ac420ae3bd5d.png)

I pip installed pynetlogo and the NetLogoLinkV61 folder is in the below location when I search for it on my pc.

Location
E:\Users\Kevin\anaconda3\Lib\site-packages\pyNetLogo\java

Should I reinstall everything since I changed versions to 6.1?

**Comment by quaquel** [comment]
I am a bit lost now. Which version of netlogo do you currently have installed? What OS are you using?

My hunch is you have the Anaconda distribution, and Windows as your OS. Is this correct?

**Comment by KevinLalor** [comment]
I have netlogo 6.1.0 installed and yes I have the Anaconda distribution and Windows 10 is my OS

**Comment by quaquel** [comment]
and you installed pynetlogo using git?

what if you don't specify ivm_home and netlogo_version? 

ivm _home should match what is returned by jpype.getDefaultJVMPath() if you want to set it yourself. So on windows you would get something like 'C:\\Program Files\\Java\\jdk-12.0.1\\bin\\server\\jvm.dll'. ivm_home is in fact a bit of a misnomer, and I still want to fix this in the next release.

**Comment by KevinLalor** [comment]
Yes I pip installed pynetlogo, everything is the same settings and code to the first screenshot all I changed was the version of netlogo I was using and then it couldnt find the  netlogolinkv6.

I've just ran the link there ,(leaving out jvm_home), and it opened netlogo up , so that problem is gone now! 

Thank you again

**Comment by quaquel** [comment]
finally had a chance to look at this. It seems my suggested monkeypatch worked at least on my Mac. I have created a new release on pypi which should support netlogo 6.2.
