### ISSUE TITLE
repeat_report with aggregate and agent-level variables 

### ISSUE THREAD

**Issue by Vayel** [quaquel/pyNetLogo#4]
I am using the library to interact with the model `Wolf and Sheep Predation` and I'd like to do something like this:

```python
netlogo.report_many(['[speed] of sample-car', '[xcor] of turtles'], 100)
```

But I obtain an (expected) error due to dimension incompatibility in the pandas dataframe. As a fix, I did this:

```python
output = defaultdict(list)
for _ in range(100):
    netlogo.command('go')
    output['sample-car'].append(netlogo.report('[speed] of sample-car'))
    output['cars'].append(netlogo.report('[xcor] of turtles'))
```

Which is obviously less efficient than `report_many`. How difficult would it be to detect incompatible output dimensions and to adapt the type of the returned datastructure accordingly?

**Comment by quaquel** [comment]
I am unsure what you try to achieve. `report_many` does not yet exist so I don't know how to read your code.

Looking at the second example, there is another problem. Looping over go inside python is very slow. In fact it is about 100 times slower than having the loop execute inside netlogo. So the general solution would be to create an entire go routine as a python string and send this to netlogo as a single command.

See https://github.com/quaquel/EMAworkbench/blob/master/ema_workbench/connectors/netlogo.py for an example of what that might look like

**Comment by Vayel** [comment]
> I am unsure what you try to achieve. `report_many` does not yet exist so I don't know how to read your code.

Sorry, I meant `repeat_report`.

> Looking at the second example, there is another problem. Looping over go inside python is very slow. In fact it is about 100 times slower than having the loop execute inside netlogo.

This is why I wanted to use `repeat_report`.

> So the general solution would be to create an entire go routine as a python string and send this to netlogo as a single command.

What I am looking for is indeed [`run_experiment`](https://github.com/quaquel/EMAworkbench/blob/master/ema_workbench/connectors/netlogo.py#L120). Why does `repeat_report` have a different behavior?

**Comment by quaquel** [comment]
repeat_report is built after the equivalent function in the RNetLogo library. The loop is executed inside Java.
