### ISSUE TITLE
Setup dependencies of pynetlogo on install_requires

### ISSUE THREAD

**Issue by j3mdamas** [quaquel/pyNetLogo#43]
Hi,
Is there a particular reason for not stating the dependencies (pandas, numpy, scipy, JPype1) on the `install_requires` of the setup command? This would make the installation much smoother. I can make a PR, if you want, but I am not sure if there are particular versions of the dependencies that would be more suitable.

**Comment by quaquel** [comment]
it is very deliberate because in my experience using setup.py with explicit dependencies can easily break a python environment. I have had this happen to me too often over the last several years.

**Comment by j3mdamas** [comment]
Thanks for the very quick answer. I haven't faced that, but that's probably because I mostly create virtual environments from scratch.
Maybe a `requirements.txt` file would be a nice to have instead, so that the person can just run `pip install -r requirements.txt`.

**Comment by quaquel** [comment]
might indeed be a good idea and should be quite easy to add.

**Comment by j3mdamas** [comment]
The simplest is:

```
JPype1
numpy
pandas
scipy
```

but something more controlled could be:

```
JPype1>=1.3,<1.4
numpy>=1.20,<1.21
pandas>=1.2,<1.3
scipy>=1.6,<1.7
```

**Comment by quaquel** [comment]
closed with https://github.com/quaquel/pyNetLogo/commit/0ab7e00fd126a40ce3c6d907b11fa3523521eac1
