### ISSUE TITLE
Documentation misuses Sobol Sampling

### ISSUE THREAD

**Issue by Wolgo** [quaquel/pyNetLogo#46]
https://github.com/quaquel/pyNetLogo/blob/b944208036c9ef7a9b0b31c8c890a05cdb73f98d/docs/source/_docs/pyNetLogo%20demo%20-%20SALib%20sequential.ipynb#L119

Quite simply running the example code with n = 1000 will give the warning:
`        Convergence properties of the Sobol' sequence is only valid if
        'N' (1000) is equal to '2^n'.
`
It would be good to alter this to be 1024 to avoid giving a "bad" example usage.

**Comment by quaquel** [comment]
yes, I noticed the change in behaviour in SALib recently myself as well and this is an easy fix.
