### ISSUE TITLE
Default NetLogo cannot be found

### ISSUE THREAD

**Issue by AgnesResto** [quaquel/pyNetLogo#49]
Hello,

I'm trying to run pynetlogo, but I'm getting this error:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/43544010/155390969-d3130566-cc12-4f15-b2f9-8a2c140166fb.png">

I built NetLogo (https://github.com/NetLogo/NetLogo/wiki/Building) in a Linux system (centOS) and have Liberica JDK 8 installed. The warning comes up when core.py is trying to check if the default extension folder exists. It's checking under an 'app' folder that I don't have in my NetLogo folder. 

Do you know what I should do in this case?

Thanks,
Agnes

**Comment by quaquel** [comment]
The type error seems to be due to something being wrong in the error message string. It is now a tuple which is indeed wrong. It should be replaced with

```python
('could not find default NetLogo '
 'extensions folder. Extensions not '
 'available')
'''

No experience with building NetLogo on Linux so I can't comment on why the extension folder is not there or where it should be.
