### ISSUE TITLE
Multiprocessing using more than one pool worker doesn't iterate

### ISSUE THREAD

**Issue by shy-r** [quaquel/pyNetLogo#52]
I followed Example 3 to set-up multiprocessing where I am trying to imitate BehaviorSpace in Netlogo.

```
`def initializer(modelfile):
    import pyNetLogo
    global netlogo
    netlogo = pyNetLogo.NetLogoLink(gui=False)
    netlogo.load_model(modelfile)

def simulation(i):
    import pandas as pd
    netlogo.command('import-data')
    netlogo.command('set random-seed '+str(i))
    temp = pd.DataFrame(netlogo.report_while(('ticks','agent','status'), 'not endrun?', command='go'))
    temp.rename(columns = {0:"time", 1:"agent",2:"status"}, inplace=True)
    temp['seed'] = i
    print('Run #'+str(i)+' Completed')
    return temp`
```

However, when I create define the multiprocessing code with a pool of 2 or more workers, it doesn't seem to iterate properly.
```
`if __name__ == '__main__':
    numsimulations = range(1,3)
    with Pool(2, initializer=initializer, initargs=(modelfile,)) as pool:
        output = pd.DataFrame()
        for entry in pool.map(simulation, numsimulations):
            output = output.append(entry)`
```

My model output gives that the random-seed value changes from 1 to 2, but the values of agent and status are exactly the same though the random seed is different.

When I try the same code with one process worker - Pool(1, initializer=initializer, initargs=(modelfile,)) as pool:, the model outputs for random-seed 1 and random-seed 2 are correct. Is there something I am doing wrong?

**Comment by quaquel** [comment]
Not sure what is going wrong, but one possibility is that you want to run each seperate process with its own working directory.

**Comment by shy-r** [comment]
Thanks for the quick reply, Jan! I'm a bit new to multiprocessing, could you tell me what I should modify in my code to have the process run in its own working directory?

**Comment by quaquel** [comment]
I checked the syntax of random-seed in netlogo, and it seems your syntax for setting the random number seed is not correct. It should just be "random seed 1234", so without the set statement. Anyway, glad you found an alternative solution for what you are trying to do.
