### ISSUE TITLE
Support and test NetLogo 6.3

### ISSUE THREAD

**Issue by EwoutH** [quaquel/pyNetLogo#60]
Currently NetLogo is tested in multiple versions, up to version 6.2. The latest NetLogo version, [6.3.0](https://ccl.northwestern.edu/netlogo/docs/versions.html#version-630-september-2022), has many performance and compatibility improvements due to the bundling of Java 17. It would be useful to check for compatibility and start testing this (in CI).

**Comment by quaquel** [comment]
I have never used CI for these tests and just ran them locally. The reason for not running them through CI was that it was difficult to configure the environment for it.

How have you been trying to run these tests?

**Comment by quaquel** [comment]
did anything change in the java API? There was a chance from 6.0 to 6.1, but 6.2 was the same as 6.1.

**Comment by quaquel** [comment]
My hunch is that the tests are failing because the tests assume that JAVA, jpype, and NetLogo are available. I have not mocked out any of this.

**Comment by quaquel** [comment]
Also, there are hardly any actual unit tests. Instead, I have tended to use the examples for testing instead.

**Comment by steipatr** [comment]
> Currently using NetLogo 6.3 with PyNetlogo crashes with:
> 
> ```
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> Cell In[11], line 13
>      10 os.environ["JAVA_HOME"] = 'C:/Program Files/NetLogo 6.3.0/runtime/bin/client/'
>      12 import pyNetLogo
> ---> 13 netlogo = pyNetLogo.NetLogoLink(gui=True)
>      15 netlogo.load_model("C:/Users/Ewout/Documents/GitHub/SEN1211-earthquake-project/models_netlogo/earthquake_model.nlogo")
>      16 netlogo.command('setup')
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyNetLogo\core.py:239, in NetLogoLink.__init__(self, gui, thd, netlogo_home, netlogo_version, jvm_home, jvmargs)
>     236 if not jpype.isJVMStarted():
>     237     jars = find_jars(netlogo_home)
> --> 239     netlogolink_jar = jar_name[self.netlogo_version]
>     241     jars.append(os.path.join(PYNETLOGO_HOME,
>     242                              'java', netlogolink_jar))
>     243     joined_jars = jar_sep.join(jars)
> 
> KeyError: '6.3'
> ```
> 
> #61 should fix this specific crash. No idea if it actually works or just crashes further in the progress.

I ran into an issue with Java Runtime versions applying this fix:

> Exception in thread "main" java.lang.UnsupportedClassVersionError: 
>   has been compiled by a more recent version of the Java Runtime (class file version 55.0), 
>   this version of the Java Runtime only recognizes class file versions up to 52.0

I think this is because of the JRE version that my organization uses (8, or "class file version 52.0"), and NetLogo 6.3 requiring v9/class file version 55.0. I alleviated the issue by moving back to NetLogo 6.2. Just dropping a note here in case anyone else struggles with this. Just to be clear, this is not a pyNetLogo bug.
