### ISSUE TITLE
docs/introduction.ipynb crashes on cell 13 (`energy_df = netlogo.repeat_report()`)

### ISSUE THREAD

**Issue by EwoutH** [quaquel/pyNetLogo#65]
The introduction notebook crashed on cell 13:
```
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.
```

See for a full error log cell 13 of https://github.com/EwoutH/pyNetLogo/blob/introduction-set-globals/docs/source/_docs/introduction.ipynb.

I validated the same error occurs with the unmodified notebook.

How to reproduce: Run [`introduction.ipynb`](https://github.com/quaquel/pyNetLogo/blob/master/docs/source/_docs/introduction.ipynb).

**Comment by EwoutH** [comment]
@quaquel I investigated this issue a bit further. I believe it's an error of [this type](https://stackoverflow.com/a/4675383/19370072).

![Screenshot_100](https://user-images.githubusercontent.com/15776622/223514849-153d4cc4-c139-473d-b3dd-743e99606deb.png)

Which is quite logical, since the number of wolves and sheep varies over time, so the length of the lists `[energy] of wolves`, `[energy] of sheep` and `[sheep_str] of sheep` also varries.

**Comment by quaquel** [comment]
This makes sense indeed. Now we have to come up with a fix,
