### ISSUE TITLE
Load 3D models by pyNetlogo

### ISSUE THREAD

**Issue by PK4teens** [quaquel/pyNetLogo#71]
Hi,i'm using pyNetlogo to load 3D models "Airplane landing 3D" of Netlogo on python. Before that i succeeded in loading "wolf sheep predation" model by imitating the Example 1 on https://pynetlogo.readthedocs.io/en/latest/_docs/introduction.html. But when i run my coad and try to load the 3D model , it pops up a window named 3D View:
Netlogo could not load the JOGL native libraries on your computer.

Write bugs@ccl.northwestern.edu for assistence.

java.lang.UnsatisfiedLinkError:Can't load library:
C:\Users\86181\PycharmProjects\pythonProject2\natives\windows-amd61\gluegen_rt.dll

then it pops up another window:
Error in loading model: java.lang.reflect.invocationTargetException

After closing two windows,the model opens but doesn't work.When i click setup, nothing happens.
After reading, I think it's because i don't have the dll file it needs, so i download a JOGL library and put it in the path it demands. It doesn't work. 
So i would like to know if i should declare the dll path in my python project or i need to configure the dll path in environment variables? 
My netlogo version:6.3.0
pyNetlogo version 0.5.1
python version 3.8
Here is my python code:
# OK Computer

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
import sys
import os

import setuptools

sns.set_style('white')
sns.set_context('talk')
import pynetlogo

netlogo = pynetlogo.NetLogoLink(gui=True,thd=True,netlogo_home='D:/NetLogo6.3.0',jvm_path='D:/Netlogo6.3.0/runtime/bin/server/jvm.dll')

netlogo.load_model('C:/Users/86181/Airplane Landing Example 3D.nlogo3d')
netlogo.command('setup')
x1 = netlogo.report('map [a -> [xcor] of a] sort airplanes')
y1 = netlogo.report('map [a -> [ycor] of a] sort airplanes')
# Make a plot
fig, ax = plt.subplots(1)
ax.scatter(x1, y1, s=4)
ax.set_xlabel('xcor')
ax.set_ylabel('ycor')
ax.set_aspect('equal')
fig.set_size_inches(5,5)
plt.show()

Thank you!

**Comment by quaquel** [comment]
My hunch is that the dll needs to be on the search path of the java JVM. You should be able to use the keyword `jvmargs` for this.

**Comment by quaquel** [comment]
It says that 3d view is not initialized. This is discussed in the mathematical link that I posted as well. Basically, you need to pass an argument to tell NetLogo that 3d is True. My hunch, again, is that this can be achieved through jvmargs, but I am not entirely sure.

**Comment by quaquel** [comment]
I need to look into this a bit more carefully. It seems like there is either a bug in pynetlogo, or there is something weird going on in jpype. If you want to check your self, you can explore the arguments to [startJVM](https://jpype.readthedocs.io/en/latest/api.html). The wording is rather cryptic there. 

A first test would be to replace the existing pynetlogo code with 

```python
args = [jvm_path,] + jvmargs
jpype.startJVM(* args, classpath=jars)
```

What is confusing is that jpype offers 2 ways to pass the jvm_path.

**Comment by PK4teens** [comment]
Thanks for reply. 
I tried your code like this:

    ```
    if not jvm_path:
            jvm_path = jpype.getDefaultJVMPath()

        self.netlogo_home = netlogo_home
        self.jvm_home = jvm_path
        args = [jvm_path, ] + jvmargs


        if not jpype.isJVMStarted():
            jars = find_jars(netlogo_home)
            jars.append(os.path.join(PYNETLOGO_HOME, "java", "netlogolink.jar"))

            try:
                jpype.startJVM(*args,classpath=jars)
            except RuntimeError as e:
                raise e
```
It reports error:
```
Unrecognized option: D:/Netlogo6.3.0/natives/windows-amd64/gluegen_rt.dll
Traceback (most recent call last):
  File "C:\Users\86181\PycharmProjects\pythonProject2\netlogo.py", line 18, in <module>
    netlogo = pynetlogo.NetLogoLink(gui=True,thd=True,netlogo_home='D:/NetLogo6.3.0',jvmargs=['D:/Netlogo6.3.0/natives/windows-amd64/gluegen_rt.dll'])
  File "E:\pythonProject1\pythonProject2\lib\site-packages\pynetlogo\core.py", line 201, in __init__
    raise e
  File "E:\pythonProject1\pythonProject2\lib\site-packages\pynetlogo\core.py", line 199, in __init__
    jpype.startJVM(*args, classpath=jars)
  File "E:\pythonProject1\pythonProject2\lib\site-packages\jpype\_core.py", line 224, in startJVM
    _jpype.startup(jvmpath, tuple(args),
RuntimeError: Unable to start JVM
```
It seems it can't recognize my path of JVM and raise a RuntimeError.It says:Unrecognized option,which didn't show up as original code.
I analyzed StartJVM() and the init_ in pynetlogo a little bit, and i don't know this part: 
```
jvmpath = None
    if args:
        # jvm is the first argument the first argument is a path or None
        if not args[0] or not args[0].startswith('-'):
            jvmpath = args.pop(0)
    if 'jvmpath' in kwargs:
        if jvmpath:
            raise TypeError('jvmpath specified twice')
        jvmpath = kwargs.pop('jvmpath')
    if not jvmpath:
        jvmpath = getDefaultJVMPath()
```


The jvmpath is none. If the args .pop doesn't play a role, it will not raise TypeError. It seems that when args isn't none it will then  judge whether the args[0] is none and whether it will remove args[0] to jvmpath. But if args[0] is none, is there anything can be  take out? And two requirements seems opposite?
I can't figure it out. Hopes it would not bother you and takes you too much time.

**Comment by quaquel** [comment]
No worries about the time.

I have been able to load the model.

1. jvm_args should be `"-Dorg.nlogo.is3d=true"`
2. My code

```python

# I am on an m1 mac. I just downloaded a x64 open jdk because I have x64 python and x64 netlogo
jvm_path = "/Users/<username>/Downloads/jdk-20.jdk/Contents/MacOS/libjli.dylib"

jvm_args = "-Dorg.nlogo.is3d=true"
link = pynetlogo.NetLogoLink(jvm_path=jvm_path, jvmargs=[jvm_args])


path = "/Applications/NetLogo 6.3.0/models/3D/Code Examples/Airplane Landing Example 3D.nlogo3d"

print("loading model")
link.load_model(path)
print("model loaded")

```

I changed core.py accordingly

```python
        if not jpype.isJVMStarted():
            jars = find_jars(netlogo_home)
            jars.append(os.path.join(PYNETLOGO_HOME, "java", "netlogolink.jar"))

            args = [jvm_path,] + jvmargs

            try:
                jpype.startJVM(*args, classpath=jars)
            except RuntimeError as e:
                raise e
```

**Comment by PK4teens** [comment]
Thanks for reply.
I change core.py as your guidance.Then the TypeError and RuntimeError don't occur.And I assign jvmargs as "-Dorg.nlogo.is3d=true" and run. Code as below:
```
jvm_path = "D:/Netlogo6.3.0/runtime/bin/server/jvm.dll"
jvm_args = "-Dorg.nlogo.is3d=true"

netlogo = pynetlogo.NetLogoLink(gui=True,thd=True,netlogo_home='D:/NetLogo6.3.0',jvm_path = jvm_path,jvmargs=[jvm_args])


netlogo.load_model('C:/Users/86181/Airplane Landing Example 3D.nlogo3d')
print("model loaded")
```

But the netlogo GUI reports the same error as the second comment I posted. Netlogo reports that 

```
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
```
and an error occured: 

```error in Constructor NLink:java.lang.reflect.invocationTargetException```

As I have moved the natives folder which 3D model needs to default working directory for python as Mathematica-Link said., and told Netlogo that 3d is True by passing argument in jvmargs, the JOGL should have initialized, isn't it? Is my jvm path wrong, or do I put a wrong JOGL library in the default working Python directory?
Really appreciate your help

**Comment by quaquel** [comment]
Strange and difficult for me to test since you are on a Windows machine while I am on a Mac. The GUI is not supported on a Mac. I have an old Windows PC lying around somewhere, but it will take some time to get that back up and running to do some testing.

Just so you know, I used the code and modifications as posted. I did not move the natives folder at all.

When do you get the error? Before or after initializing the link?

Also, you could try the following. Add the code below to core.py after `if not gui`. And remove this element from jvmargs.

```python
if thd:
    jpype.java.lang.System.setProperty("org.nlogo.is3d", "true")
```

**Comment by PK4teens** [comment]
I wonder if this is a problem with jvm_path? Does a 3D model need a different jvm_path from 2D model? I tried the jvm.dll in two directory(client/server) in the path runtime/bin. As your code on mac can be loaded successfully, the only difference with my code is the jvm_path. Which jvm I should use on PC to load the 3Dmodel?
Thanks for your assistance.

**Comment by PK4teens** [comment]
I downloaded a openjdk-20_windows-x64_bin and change the jvm_path to D:\openjdk-20_windows-x64_bin\jdk-20\bin\server\jvm.dll. Now the code:
``jvm_path = "D:/openjdk-20_windows-x64_bin/jdk-20/bin/server/jvm.dll"

netlogo = pynetlogo.NetLogoLink(gui=True,thd=True,netlogo_home='D:/NetLogo6.3.0',jvm_path = jvm_path)``
and the core.py:
 `` if sys.platform == "darwin":
            jpype.java.lang.System.setProperty("java.awt.headless", "true")
            gui = False
        if not gui:
            if thd:
                jpype.java.lang.System.setProperty("org.nlogo.is3d", "true")
            jpype.java.lang.System.setProperty("org.nlogo.preferHeadless", "true")``
After running the code, the waiting time seems a little longer? But it fails again and report same error.

**Comment by quaquel** [comment]
Thanks for keeping me posted. I hope to find time this week to take a look myself on windows, but I can make no promises, unfortunately.
