### ISSUE TITLE
repeat_report now returns dictionary instead of dataframe

### ISSUE THREAD

**Issue by EwoutH** [quaquel/pyNetLogo#78]
`repeat_report()` now returns a dictionary (dict) instead of Pandas DataFrame (df). This change happened somewhere between early February and now.

This should be reversed, since it's breaking behaviour, or be very clearly documented as a breaking change in v0.5.x, if intended.

The workaround for now is adding `pd.DataFrame()` around your repeat_report return variable.

**Comment by quaquel** [comment]
See commit https://github.com/quaquel/pyNetLogo/commit/98c648a5725da25a4af6c6171ca0445983beb7a4, report can return something other than a scalar, and thus you cannot always cast the results to a data frame. See also #45. 

Yes, it is a breaking change, but the only possible fix for this problem.

**Comment by EwoutH** [comment]
Can you add this informatIon in the release notes of v0.5.0 under a Breaking changes header?
