### ISSUE TITLE
issue with running ipyparallel and pynetlogo

### ISSUE THREAD

**Issue by Ladilu** [quaquel/pyNetLogo#83]
Computer: 64-bit operating system, x64-based processor, Windows 11 Pro
netlogo: 6.3.0
pynetlogo: 0.5.1
python: 3.11

I have downloaded jupyter lab and I have tried to run the following script, based on the documentation example about the usage of ipyparallel with netlogo and what I could find within the GitHub forum. I want to run a simulation many times and then attach the results to an array and manipulate it, maybe under the form of a dataframe. This is an initial code for the start:

import pynetlogo
import pandas as pd
import ipyparallel as ipp
import os
import concurrent.futures
import time
os.environ['JAVA_HOME'] = r'C:\Program Files\Java\jdk-21\bin\server'
def initializer(modelfile):
    """initialize a subprocess

    Parameters
    ----------
    modelfile : str

    """

    # we need to set the instantiated netlogo
    # link as a global so run_simulation can
    # use it
global netlogo
netlogo = pynetlogo.NetLogoLink(gui=False)
netlogo.load_model(r"C:\Users\Laura\Bass_graphml_with_qnorm.nlogo")
def run_simulation():
    #Parameters
    #----------
    #experiments 

    netlogo.command("setup")
    netlogo.command("create-network")
    # Run for 100 ticks and return the number of sheep and wolf agents at each time step
    counts = netlogo.repeat_report("num_adopted", 100, go="go")

    results = pd.Series(
        [counts[num_adopted].values.mean(), counts[num_adopted].values.max()],
        index=["Avg. adopted", "Max adopted"],
    )

    return results
cluster = ipp.Cluster(n=4)
cluster.start_cluster_sync();    
rc = cluster.connect_client_sync()
rc.ids
lview = rc.load_balanced_view()

def main():
    #with concurrent.futures.ProcessPoolExecutor() as executor:
    with concurrent.futures.ProcessPoolExecutor(max_workers=4) as executor:
        for i in range(5):
            initializer(r"C:\Users\Laura\Bass_graphml_with_qnorm.nlogo")
            run_simulation()

if __name__ == '__main__':
    start_time = time.time()
    main()
    print("--- %s seconds ---" % (time.time() - start_time))
  

   
results = pd.DataFrame(results)
results.head(10)

I can run the simulation but I get the following error:
Starting 4 engines with <class 'ipyparallel.cluster.launcher.LocalEngineSetLauncher'>
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In[4], line 54
     52 if __name__ == '__main__':
     53     start_time = time.time()
---> 54     main()
     55     print("--- %s seconds ---" % (time.time() - start_time))
     61 results = pd.DataFrame(results)

Cell In[4], line 50, in main()
     48 for i in range(5):
     49     initializer(r"C:\Users\Laura\Bass_graphml_with_qnorm.nlogo")
---> 50     run_simulation()

Cell In[4], line 31, in run_simulation()
     29 netlogo.command("create-network")
     30 # Run for 100 ticks and return the number of sheep and wolf agents at each time step
---> 31 counts = netlogo.repeat_report("num_adopted", 100, go="go")
     33 results = pd.Series(
     34     [counts[num_adopted].values.mean(), counts[num_adopted].values.max()],
     35     index=["Avg. adopted", "Max adopted"],
     36 )
     38 return results

File ~\pynetlogo\core.py:557, in NetLogoLink.repeat_report(self, netlogo_reporter, reps, go, include_t0)
    553                 result = np.array([entry.strip('"') for entry in result.split()])
    555         results[key] = result
--> 557     os.remove(value)
    559 # cleanup temp files and folders
    560 for fh in fhs:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Laura\\tnjmbzvc\\tmpykwq7nnq.txt'

I have tried to comment the line 557 but it still gives the error.

**Comment by quaquel** [comment]
1. Could try to format your code better. It is tough to read at the moment. There are various good options within GitHub flavored markdown to make it much better readable. 
2. You are mixing a process pool and ipyparallel, which are two distinct and alternative ways of running code in parallel. The first step is to decide which of the two you would like to use and why.
3. You currently have a hardcoded path to your model in `load_model`. I strongly urge you to change this to a relative pathy. Hardcoded paths are a major source of problems when trying to run stuff in parallel.

**Comment by Ladilu** [comment]
New code:
import pynetlogo
import pandas as pd
import os
import concurrent.futures
import time
os.environ['JAVA_HOME'] = r'C:\Program Files\Java\jdk-21\bin\server'
def initializer(modelfile):
    """initialize a subprocess

    Parameters
    ----------
    modelfile : str

    """
modelfile=r"C:\Users\Laura\Bass_graphml_with_qnorm.nlogo"
    # we need to set the instantiated netlogo
    # link as a global so run_simulation can
    # use it
global netlogo
netlogo = pynetlogo.NetLogoLink(gui=False)
netlogo.load_model(modelfile)
def run_simulation():
    #Parameters
    #----------
    #experiments 

    netlogo.command("setup")
    netlogo.command("create-network")
    # Run for 100 ticks and return the number of sheep and wolf agents at each time step
    counts = netlogo.repeat_report("num_adopted", 100, go="go")

    results = pd.Series(
        [counts[num_adopted].values.mean(), counts[num_adopted].values.max()],
        index=["Avg. adopted", "Max adopted"],
    )

    return results


def main():
    #with concurrent.futures.ProcessPoolExecutor() as executor:
    with concurrent.futures.ProcessPoolExecutor(max_workers=4) as executor:
        for i in range(5):
            initializer(r"C:\Users\Laura\Bass_graphml_with_qnorm.nlogo")
            run_simulation()
if __name__ == '__main__':
    start_time = time.time()
    main()
    print("--- %s seconds ---" % (time.time() - start_time))
  



   
results = pd.DataFrame(results)
results.head(10)


Error:
Cell In[8], line 45, in main()
     43 for i in range(5):
     44     initializer(r"C:\Users\Laura\Bass_graphml_with_qnorm.nlogo")
---> 45     run_simulation()

Cell In[8], line 30, in run_simulation()
     28 netlogo.command("create-network")
     29 # Run for 100 ticks and return the number of sheep and wolf agents at each time step
---> 30 counts = netlogo.repeat_report("num_adopted", 100, go="go")
     32 results = pd.Series(
     33     [counts[num_adopted].values.mean(), counts[num_adopted].values.max()],
     34     index=["Avg. adopted", "Max adopted"],
     35 )
     37 return results

File ~\pynetlogo\core.py:557, in NetLogoLink.repeat_report(self, netlogo_reporter, reps, go, include_t0)
    553                 result = np.array([entry.strip('"') for entry in result.split()])
    555         results[key] = result
--> 557     os.remove(value)
    559 # cleanup temp files and folders
    560 for fh in fhs:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Laura\\tsqm8n_m\\tmp206y58o8.txt'

I attach a notebook file with the code 
[code_for_discussion_ipyparallel_github.txt](https://github.com/quaquel/pyNetLogo/files/13965955/code_for_discussion_ipyparallel_github.txt)

**Comment by quaquel** [comment]
I kindly request you to read up on GitHub flavored markdown. I have no done a quick fix of your question, but learning it is a useful skill. 

Are you running this code in a notebook? What happens if you try to run it as a .py file? Your problem seems similar to #82.

**Comment by Ladilu** [comment]
I have checked once again in the settings app but I have always been running as an administrator.  Executing as a .py file is better but needs definitely switching to Pool instead of ipyparallel, I suspect it has something to do with the extensions.

**Comment by quaquel** [comment]
I just merged #85 which might also fix your problem. I'll try to release it on pypi later this week.
